### ISSUE TITLE
How to call the return of a function?

### ISSUE THREAD

**Issue by 0b1kn00b** [NQNStudios/kisslang#140]
If the Haxe function is like:
```haxe
function fn1(){
 return {
   fn2 : () -> true
   }
 }
```
feels like it should be

```lisp
((fn1).fn2)
```

but I'm having to use `let` at the moment

**Comment by 0b1kn00b** [comment]
```lisp
(.fn2 (fn1))
```

**Comment by NQNStudios** [comment]
Thanks for taking an interest in Kisslang! Glad you figured this out. Don't hesitate to reach out again with more questions. :)
