### ISSUE TITLE
Under some unknown conditions, pure-kiss classes break the Haxe compiler

### ISSUE THREAD

**Issue by NQNStudios** [NQNStudios/kisslang#158]
Janky error message.
```
C:/Users/natqu/repos/kisslang/kiss/src/kiss/KissFrontend.hx:20: KissG
Compiler failure
                Please submit an issue at https://github.com/HaxeFoundation/haxe/issues/new
                                                                                           Attach the following information:
    Haxe: 4.2.1+bf9ff69; OS type: windows;
                                          File "src/typing/typeloadModule.ml", line 847, characters 22-29
                                                                                                         Called from file "src/typing/typeloadModule.ml", line 847, characters 15-29
                                                            Called from file "list.ml", line 106, characters 12-15
                                                                                                                  Called from file "src/typing/typeloadModule.ml", line 945, characters 1-53
                                                                    Called from file "src/typing/typeloadModule.ml", line 1007, characters 1-35
                       Called from file "src/typing/typeloadModule.ml", line 1062, characters 11-48
                                                                                                   Called from file "src/typing/typeloadModule.ml", line 1103, characters 4-45
                                                      Called from file "src/typing/typeloadModule.ml", line 502, characters 12-69
         Called from file "src/typing/typeloadModule.ml", line 641, characters 3-24
                                                                                   Called from file "list.ml", line 106, characters 12-15
                 Called from file "src/typing/typeloadModule.ml", line 945, characters 1-53
                                                                                           Called from file "src/typing/typeloadModule.ml", line 1007, characters 1-35
                                              Called from file "src/typing/typeloadModule.ml", line 1062, characters 11-48
  Called from file "src/typing/typeloadModule.ml", line 1103, characters 4-45
                                                                             Called from file "src/typing/typeload.ml", line 165, characters 5-36
                         Called from file "src/typing/typerBase.ml", line 111, characters 22-73
                                                                                               Called from file "src/typing/typer.ml", line 421, characters 15-37
                                         Called from file "src/typing/typer.ml", line 1657, characters 10-101
                                                                                                             Called from file "src/typing/callUnification.ml", line 86, characters 11-58
                                                                Called from file "src/typing/callUnification.ml", line 193, characters 12-33
                    Called from file "src/typing/callUnification.ml", line 194, characters 9-21
                                                                                               File "src/core/globals.ml", line 117, characters 1-7: Assertion failed

```

**Comment by NQNStudios** [comment]
@0b1kn00b I got this deep compiler error when trying to import a tink_syntaxhub-generated class from a haxelib.

The best explanation I can think of is that things get screwy when onTypeNotFound() is used to try to find a class in a different haxelib from the current one's class path. When I added a .hx boilerplate file for the class, it worked.

EDIT: I'm having trouble wording this clearly. Basically, I think that a haxelib can't *export* a Kiss class unless that class uses a .hx file with the build macro.

**Comment by 0b1kn00b** [comment]
This is definitely compiler team territory, and I guess see what you get. I've butted heads with them on occasion over the insistence it's the bug submitters responsibility to isolate the issue.

**Comment by 0b1kn00b** [comment]
With your permission, I'll submit this to the haxe repo

**Comment by NQNStudios** [comment]
For now, I would rather not. I prefer to reproduce bugs like this in a simple Haxe-only example before bringing them to the Haxe team, because I understand they won't have time to understand my codebase and Kisslang's architecture.

I did try to isolate what caused the error, but my theories weren't giving consistent results. These theories were:

- That `KissFrontend.use()` was only working within `kiss` itself, not external projects declaring `-lib kiss` and relying on extraParams.hxml. This turned out not to be true, because as of 39c760e2bfc5fb261a06c80ebc65af2ab440f61b and de3e336b0306a1923c18283de3fb2ba2d0036f80 the tests show this use case working in a basic template project.
- That tink_syntaxhub was unable to resolve missing types if they were in the classpath of a `-lib` dependency (this wasn't it either). In the case that was throwing the error, the FrontEnd was finding the right source file and running `Kiss.build()` successfully.

My current theory would have to be that a Kiss class that's generated in the old style, cannot import a kiss class that's generated in the new way. Maybe because of the order the compiler runs build macros and compiler macros -- I decided to stop digging into it unless this error pops up again. Because in the end I actually scrapped the file I was writing and didn't even add it to the repo.

EDIT: Come to think of it, even that theory is wrong, at least within `kiss`, because I added tests to BasicTestCase (a build-macro class) which involve importing pure-Kiss classes. And those tests are working. Maybe the theory could still be right in the `-lib kiss` use case.

**Comment by NQNStudios** [comment]
This is murky enough, and hasn't resurfaced the more I use pure-kiss classes. Closing for now.

**Comment by NQNStudios** [comment]
Having just said that, I reproduced the error. 😆 

I'm pretty sure it happens when a `.hx` class does BOTH of the following:

* Invoke kiss.Kiss.build() to add fields to itself
* import a class that is defined without a .hx file

And if pure-kiss class definitions become the norm, I don't think that's a case worth fixing.
