### ISSUE TITLE
automatic interface/typedef implementation

### ISSUE THREAD

**Issue by NQNStudios** [NQNStudios/kisslang#83]
I already made a good start on this in the Main.implement() static function which is already hooked to a command-line command.

Especially useful for making new NAT playgrounds and Hollywoo directors

**Comment by NQNStudios** [comment]
The next thing needed before I close this, is support for generic interfaces.

**Comment by 0b1kn00b** [comment]
I didn't realise this would be putting messages in your feed.

**Comment by NQNStudios** [comment]
No worries!

**Comment by NQNStudios** [comment]
If I put off doing hollywoo-godot, I can justify closing this without implementing the generic interface case.
